videojs/mux.js

lib/mp4-generator.js, lib/stream.js, lib/transmuxer.js, test/transmuxer-test.js
We need to set the baseMediaDecodeTime so that MSE knows where, in time, it should plop segments
=> Start setting the baseMediaDecodeTime in fragments

lib/caption-stream.js, lib/transmuxer.js, test/caption-stream-test.js, test/transmuxer-test.js
Captions require information about the start time of their associated segment in order to properly place them in the media timeline and that information is not available until after the entire segment is parsed. Buffer captions in the coalesce stream until the segment is ready and then calculate start and end times so that downstream consumers don't have to do it themselves.
=> Collect captions in the coalesce stream before emitting

lib/caption-stream.js, test/caption-stream-test.js
Shift to a data model in Cea608Stream that more accurately simulates the theoretical captions decoder from the spec. Use the new model to implement roll-up captions mode with 2, 3, and 4 row support.
=> Add roll-up CEA-608 captions mode

debug/index.html, lib/transmuxer.js, test/transmuxer-test.js
Transmuxer debugging page now has changes that allow for greater debugging options by enabling the user to force the transmuxer to output only audio or only video segments. Helps you narrow down which of the two segment types is causing a problem with MSE.
Required changes the transmuxer to support non-remuxed output. Added tests to verify that the output from the transmuxer can be specified with an options-object at creation.
=> Selective output

lib/caption-stream.js, test/caption-stream-test.js
In pop-on and roll-up modes, move the "cursor" back one cell and clear the character that is traversed when a backspace is received. We don't yet support any cursor-movement commands besides this one so the backspace is always applied to the last position in the base row for the current captioning mode.
=> Support the backspace command code

lib/stream.js, lib/transmuxer.js, test/transmuxer-test.js
A laundry list of fixes in the PR (in roughly top-down order):
* Rewrote transport packet parsing to be more robust when confronted with strange segmentation strategies - again!
* On a ~~BMDT reset (PTS - discontinuity)~~ the first segment, we now remove AAC frames that extend before the first PTS of the video track.
* Extended tracking previously done with `timelineStartDts` to track both audio and video tracks and both dts and pts values for each.
* Caption `startTime` and `endTime` are now relative to the last time base media decode time was set to zero.
=> Reset bmdt

lib/transmuxer.js, test/transmuxer-test.js
AAC is defined in both mpeg-2 and mpeg-4 specs and I don't think this distinction matters for our purposes.
=> Ignore the "mpeg version" bit in the ADTS header when looking for the syncword

lib/m2ts/m2ts.js, test/transmuxer-test.js
* Moved parsePes to the ElementaryStream *after* the entire packet has been received
* Fixed a minor bug that resulted in PTS/DTS values potentially being off by 1
* Fixed/moved tests since a major portion of the TransportParseStream's work is now done in ElementaryStream
* Added a case which tests header reassembly across packets
=> Fix PES Parsing

lib/flv/transmuxer.js, lib/mp4/transmuxer.js, package.json, test/index.html, test/karma.conf.js, test/transmuxer-test.js
There are cases when nalUnit streams may not start with an AUD and this can result in `h264Frame` being undefined as we parse more
=> H264frame fix

lib/mp4/transmuxer.js, test/transmuxer-test.js
The only change is to how we track emittedTracks so that we can hold-off triggering 'done' until after the segment has been completely flushed in the non-combined output mode.
=> Fixes for non-combined output with separate audio/video fragments and sourceBuffers

lib/m2ts/m2ts.js, test/transmuxer-test.js
The basic change is to construct only the first 31-bits of the 33bit pts/dts values with bitwise ops since bitwise operations always work on *signed* 32bit integers. The remaining two bits are then added via math-wise operations.
=> Fix for large PTS/DTS values resulting in negative values

lib/m2ts/m2ts.js, lib/mp4/transmuxer.js, test/transmuxer-test.js
Allow specifying a time (in 90khz) to consider as the `baseMediaDecodeTime` of the first segment pushed through the transmuxer. Subsequent segments will be placed relative to the first in time.
=> Allow a base-baseMediaDecodeTime to specified when the transmuxer is constructed

lib/mp4/transmuxer.js, test/caption-stream-test.js
Instead of outputting ID3 and captions in absolutely time, go back to placing them relative to the start of the *first* segment since we last set the `baseMediaDecodeTime`. Let `videojs-contrib-media-sources` do the translation in time based on `timestampOffset` which follows what we must do in the Flash case.
=> Do not output ID3 and caption times based on baseMediaDecodeTime

lib/codecs/h264.js, lib/m2ts/caption-stream.js, lib/m2ts/metadata-stream.js, test/caption-stream-test.js, test/id3-generator.js
* SEI nal units are purged of any emulation prevention bytes
* SEI parsing now works with SEI nals containing multiple messages
* Caption parsing now treats preamble address codes as spaces, improving readability
* Caption parsing now correctly ignores redundant control codes
* Captions packets are reordered based on PTS before being processed to handle out-of-order caption packets arising from B-frames
* All sizes or lengths in ID3 tags and frames are in "sync-safe integer" format - parse them correctly
* Fix tests which were not creating the correct tags
=> Caption ID3 Parsing Improvements

lib/mp4/transmuxer.js, test/transmuxer-test.js
1. Change how we calculate the baseMediaDecodeTime to correctly place segments without introducing a gap that start with a non-zero compositionTimeOffset for the first frame
1. Allow audio track metadata to change as we parse segments
* Previously the emitted fragment would have metadata copied from the first segment we ever received and the meta data would never change even as the incoming segments changed audio parameters
=> BaseMediaDecodeTime & Audio Metadata fixes

lib/m2ts/metadata-stream.js, package.json, test/metadata-stream-test-worker.js, test/metadata-stream.test.js
While the functions decodeURIComponent and unescape exist in the global scope, window is not available in all scopes (for instance, in the scope of a web worker).
=> Remove window references in parsing functions of metadata stream

debug/index.html
Based on a checkbox we selectively recreate the transmuxer and mediasource allowing for the debugging of the transmuxer output when it is in a non-fresh state. This is particularly useful for testing side-effects caused by earlier segments such as ensuring proper baseMediaDecodeTime and GOP-Fusion results
=> Added support for multiple input files in the m2ts side

lib/m2ts/caption-stream.js
This patch supports the use of the eighth note special character in basic 608 captions.
=> Eighth note support

lib/flv/transmuxer.js, lib/m2ts/caption-stream.js, test/caption-stream.test.js
* added a getCharCode function to put the code in a central location
* only insert one space for codes that we don't support
* trim spaces before and after a row of captions before we emit
* ignore caption channels other than channel one
* updated tests to use a channel (previously non-existent)
* Added a test to decode multi channel captions (we only do the first channel)
* Verify that config and track are defined when we go to finish an FLV video frame
=> Add channel test and fix flash

debug/index.html
As segments are produced by the transmuxer, we need to store them in-memory until the input is flushed. This was accidentally deleted in an earlier patch and caused the debug page to never show any output.
=> Restore segment buffering

lib/mp4/transmuxer.js, test/transmuxer.test.js
The first iteration of holding onto the last-segment's-GOP and attempting to prepend that GOP to the next segment.
The `flush` functions are much nicer - far fewer variables; limited global mutations; fit on one screen! The bulk of the work has been moved to functions that perform limited parts of what the giant `while` loop used to do. The functions are written so that they do not mutate their parameters for sanity reasons.
While this might be slightly less performant, it is still O(n) and is much easier to reason about the steps that are happening on a flush.
The last GOP in a segment is held onto and prepended onto the next segment providing the next segment is greater than the GOP in time AND the next segment is within 10 seconds of the GOP.
=> GOP-FUSION

lib/m2ts/caption-stream.js
We were displaying some other glyph instead of the eighth-note when we detected a musical-note character in the CC stream.
=> Use the correct unicode for the eighth note character

debug/index.html, lib/aac/index.js, lib/mp4/transmuxer.js, lib/utils/stream.js, test/transmuxer.test.js
Experimental attempt to have the transmuxer pipeline get smarter about what to do with the data that is passed into it. 
* Added the ability to tear down the pipeline
* Added a sniffer function that checks to see if the data is likely an AAC by checking to see if it starts with an ID3 tag
* The pipeline creation now happens when the first segment or when a different type of segment is passed in
* The audio track is saved so that the `timelineStartInfo` data is preserved between pipeline changes
=> Have the transmuxer pipeline automatically configure itself based on input

lib/m2ts/caption-stream.js, test/caption-stream.test.js
This PR is to fix an issue for roll-up captions where the rows would stack on top of each other.
=> Display roll-up caption rows as one cue to preserve ordering

lib/codecs/h264.js, test/transmuxer.test.js
This fixes the bug we were seeing where the aspect ratio was incorrect in chrome. This fix parses out the pixel width nal packets and scales the video accordingly.
=> Fixed aspect

lib/mp4/mp4-generator.js
Tested by ensuring that "'Uint8Array' is undefined" error is no longer being thrown in IE8, however, due to other errors, was not able to test full flow through with IE8.
=> If Uint8Array is undefined (IE8) don't set up MP4 generator functions

.npmignore, debug/index.html, lib/aac/index.js, lib/codecs/h264.js, lib/m2ts/caption-stream.js, lib/mp4/transmuxer.js, lib/tools/mp4-inspector.js, lib/utils/stream.js, package.json, scripts/server.js, test/caption-stream.test.js, test/transmuxer.test.js
* Support automatic AAC parsing by reconfiguring the pipeline
* Updates to the debug page to make it more useful and adding the ability to save the output of the transmuxer locally
* Add information about the output initialization segment to the object returned by the transmuxer
* Fixed a bug where we weren't parsing aspect ratio from sps
* Ignore empty nal units
* Fix a bug where a condition would be true even if frames.length was zero
* Roll-up captions are now emitted as a single cue point instead of one-per-line
=> Mux.js changes for multiple audio track support

lib/tools/mp4-inspector.js
Correctly parse tfdts with 64-bit fields. We can't avoid the possibility of overflow but values that aren't too big for js numbers should work.
=> Add support for v2 tfdt

lib/flv/transmuxer.js, lib/m2ts/m2ts.js, lib/m2ts/timestamp-rollover-stream.js, lib/m2ts/ts-correction-stream.js, lib/mp4/transmuxer.js, test/transmuxer.test.js
Every 26 hours the PTS value resets to 0. We need to detect this condition in the Muxer and add a value to make the PTS values continuous.
* Rollover conditions:
* Between a single PES packet's DTS and it's PTS
* Between a PES packet's PTS and the next packet's DTS
* There is a spec for M2TS playback over MSE  https://w3c.github.io/media-source/mp2t-byte-stream-format.html#mpeg2ts-discontinuities
* Detect when the PTS OR DTS value rolls over
* Adjust PTS and DTS values to be always increasing by adding `n*2^33` where `n` is the number of rollovers.
* Attach a `TSCorrectionStream` to the end of the `ElementaryStream` or `AacStream` in the pipeline to make these adjustments
* Tests
=> Timestamp Rollover

lib/m2ts/metadata-stream.js, test/metadata-stream.test.js
The special PRIV frame that specifies the timestamp in raw AAC data would not itself receive a timestamp since it was already parsed when the base timestamp was set. Add special case handling for that ID3 tag so that it does not end up with a cueTime of NaN when picked up by the CoalesceStream in the MP4 transmuxer.
=> Set the PTS and DTS for TS timestamp ID3 tags

lib/mp4/mp4-generator.js, test/mp4-inspector.test.js, test/transmuxer.test.js
Switch to using version 1 tfdt boxes to allow up to 64-bits for the baseMediaDecodeTime. 
Since we use a 90kHz clock for the BMDT, we can exceed a 32-bit value after ~13.256 hours of video. This can cause a problem with live-streams or extremely long VODs as the BMDT will wrap around and playback will likely break.
=> Added support for generating version 1 TFDT boxes

lib/tools/ts-inspector.js, test/ts-inspector.test.js
This changes the output of the ts inspector to include both `pts` and `ptsTime`. `pts` is the timestamp value on the 90khz clock and `ptsTime` is the timestamp value converted into seconds.
=> add ptsTime to ts inspector output

lib/utils/stream.js, test/stream.test.js
Using a callback to mutate the listeners (e.g. removing yourself), previously
changed the iterated array, causing bugs.  Remove the problem by always copying
the array, so on()/off() become safe to call at any time.
=> Allow add/remove listeners in callbacks (#119)

debug/index.html, lib/mp4/transmuxer.js, test/transmuxer.test.js
Currently we generate and attach an initialization segment (`ftyp` and `moov` boxes) to the mp4 we generate for every ts segment. Adding this init segment for each segment causes a noticeable hiccup in the audio along segment boundaries. Only attaching an init segment on timeline changes when `baseMediaDecodeTime` is set resolves this issue.
Requires [pull request](https://github.com/videojs/videojs-contrib-media-sources/pull/104)
Only create a single mp4 init segment whenever `setBaseMediaDecodeTime` is called, otherwise just create the `moof` and `mdat`.
=> Create mp4 init segment only for first segment of timeline

lib/flv/transmuxer.js, test/transmuxer.test.js
Currently, the `VideoSegmentStream` in the FLV transmuxer holds a reference to an `h264Frame` object across segment boundaries even though it always finishes the frame at the end of every flush. This means that on the next flush, that same frame will be finished a second time, causing a duplicate frame append. This also happens on replays where the last frame of the last segment will be added to the tags in the first segment.
This change sets `h264Frame = null` after every call to `finishFrame`. Also changed the metadata and extra data tags to have timestamps based on dts instead of pts to make sure tags are ordered correctly.
=> Set h264Frame to null after we finish the frame

package.json
The browserify-shim doc says it should be at the devDependencies instead of the dependencies section ([ref](https://github.com/thlorenz/browserify-shim#1-install-browserify-shim-dependency)).
When you require mux.js from a project, it will pull the shim, and will complain for missing browserify peer dependency. See:
```
├─┬ videojs-contrib-hls@3.6.5
│ ├─┬ aes-decrypter@1.0.3 
│ │ └── pkcs7@0.2.3 
│ ├── m3u8-parser@1.2.0 
│ ├─┬ mux.js@3.0.2 
│ │ ├── UNMET PEER DEPENDENCY browserify@>= 2.3.0 < 14
│ │ └─┬ browserify-shim@3.8.12 
```
=> Move browserify-shim to the devDependencies

lib/flv/coalesce-stream.js, lib/flv/transmuxer.js, test/transmuxer.test.js
If there is an audio and video track in the segment but no audio data, (seen in several playlists with alternate audio tracks and no audio present in the main TS segments.), the `CoalesceStream` would never finish its flush process and emit a `done` event. This would cause the player to become stuck waiting to append to the buffer, with no errors. 
This change accounts for this possibility and allows `CoalesceStream` to complete its flush cycle with an empty audio track. I also pulled `CoalesceStream` out into its own file to help work towards needed project maintenance .
=> fix coalesce stream in FLV transmuxer to account for missing audio data in pending tracks

lib/data/silence.js, lib/mp4/transmuxer.js, lib/utils/clock.js, test/transmuxer.test.js, test/utils.clock.test.js
If an audio append start time is provided, and the next audio segment starts greater than a frame's duration from that time, but is within a half second from that time, fill the gap (up to the nearest whole frame) with silence.
=> Fill audio gaps at start of segment with silence

lib/flv/tag-list.js, lib/flv/transmuxer.js
some important information wasn't being attached to the tags outputted by the flv transmuxer. 
This adds them on
=> output extra flags on flv tags

lib/mp4/transmuxer.js
`this.extendFirstKeyFrame_` should not throw an exception if there is only one GOP and should become a NOOP in that case.
=> Transmuxing can fail if there are less than two GOPs

lib/m2ts/timestamp-rollover-stream.js, lib/mp4/transmuxer.js
https://github.com/videojs/videojs-contrib-hls/issues/1056
The above issue stems from two key things. 
* the `TimestampRolloverStream` doesn't reset its `referenceDTS` value on discontinuities. This wasn't really an issue because of the way we use `baseMediaDecodeTime` to shift segments to the correct time on discontinuities, so it didn't matter if the transmuxer treated a segment on a discontinuity as a rollover since `baseMediaDecodeTime` would shift it correctly regardless.
* each `type` (`video`, `audio`, `timed-metadata`) has its own independent `referenceDTS`. This is important because the rollover for video may be in a different segment than the rollover in audio if it is near segment boundaries. However, in the case of the issue linked above, because only the ads have ID3 tags, …
=> reset TimestampRolloverStream on discontinuities

lib/m2ts/m2ts.js, package.json, test/transmuxer.test.js
Where `complete` is defined as any time `PES_packet_length` matches the data’s length OR is a video packet.
Works around an issue with incomplete packets getting sent down the pipeline when the source has audio PES packets split between segments.
=> Only flush PES packets from TS parsing front end when they are complete

lib/flv/transmuxer.js, lib/m2ts/caption-stream.js, lib/mp4/transmuxer.js, test/caption-stream.test.js
Sometimes the same segment is pushed twice to the transmuxer. For instance, an initial seek pushes the first segment twice, and a rate switch sometimes pushes the same segment but at two different rates. As you might expect, this messes with caption processing.
The general idea is that we track the most recently received DTS, and if we receive any DTS less than that, we return without processing the caption data. There is a caveat, which is when data for single DTS is split across segments. For that case, we need to ignore the first packet, but not anything after, since it is a new segment. See the comments in the code.
I've marked this as WIP since I'm not sure if my assumption about monotonically increasing DTS values is correct. Also, this breaks when seeking back in time, and I'm not …
=> Caption fixes (incl duplicate caption processing)

lib/m2ts/m2ts.js, test/transmuxer.test.js
Segments can contain multiple audio and video tracks. Currently mux.js does not take this into account, so when there are multiple, they get combined into a single stream. This can cause playback issues or distorted audio. 
https://github.com/videojs/videojs-contrib-hls/issues/994
https://github.com/videojs/mux.js/issues/106
https://github.com/videojs/videojs-contrib-hls/issues/1247
This change makes sure the transmuxer uses the track with the lowest identifier, ignoring extra tracks.
I'm not quite sure if it is common for streams to have multiple timed-metadata tracks, and we have not gotten any reports around multiple timed-metadata tracks, so I have kept the functionality of combining all timed-metadata tracks into a single stream.
=> Use the first audio and video tracks in the PMT

lib/m2ts/caption-stream.js, test/caption-stream.test.js
According to some real-world caption data for CC4, the currently active data channel is tracked on a per-field basis, not globally for all captions.
Comments about the efficiency of my solution would be particularly appreciated.
=> Set active data channel per-field instead of globally

lib/m2ts/m2ts.js, test/transmuxer.test.js
PES packets can be poorly formatted to have padding bytes at the end, but not include those padding bytes in the PES_packet_length value. This would cause the length match comparison to make sure we've gotten the compete packet to fail. The change here will allow flushing a packet if we have exactly or more than enough data to meet the PES_packet_length.
=> flush pes packets when there is enough data

lib/m2ts/caption-stream.js, test/caption-stream.test.js
I found a source feed which broke the fix I made in #158 :sob: 
Thankfully, a fix wasn't too hard. It was just receiving packets with the same dts before the segment switch, so now it keeps track of how many packets it should ignore (i.e. it better infers where the segment boundary is).
Updated the relevant test to account for such a situation.
=> Better fix for ignoring of duplicate segments

lib/mp4/probe.js, lib/utils/bin.js, test/utils.bin.test.js
javascript bitwise operations convert operands to signed 32 bit integers, this, the output of bitwise ops will be signed 32bit ints, however, we want them to be unsigned. `>>> 0` ensures the value will be unsigned
=> fix mp4 probe bitwise operations

lib/mp4/transmuxer.js, test/transmuxer.test.js
I registered the issue #187 .
Fixed code in transmuxer.js file.
I added ```isNonSyncSample``` property at the createDefaultSample function used by ```VideoSegmentStream```.
```isNonSyncSample``` property semantics by MP4_spec;
"The flag sample_is_non_sync_sample provides the same information as the sync sample table [8.6.2].
When this value is set 0 for a sample, it is the same as if the sample were not in a movie fragment and
marked with an entry in the sync sample table (or, if all samples are sync samples, the sync sample table
were absent)."
```isNonSyncSample``` property is already used by the mp4-generator.js file.
```js
videoTrun = function(track, offset) {
var bytes, samples, sample, i;
samples = track.samples || [];
offset += 8 + 12 + (16 * samples.length);
bytes = …
```
=> fix: remuxed video corruption fix at ie, edge

lib/m2ts/caption-stream.js, test/caption-stream.test.js
I normally like to split up my changes a bit more, but these are kind of interlinked.
As the branch name implies, I started this as a feature for paint-on, but had to cascade some changes to make things compatible, and doing so made me catch a bug.
In essence:
- Paint-on mode is now supported
- Roll-up puts captions in the proper row, rather than always being fixed to the bottom row
- The roll-up window can shift around without deleting contents (as per the spec)
- Switching to roll-up clears displayed and non-displayed memories
- Fixed a bug where backspace wouldn't actually backspace for pop-on captions that weren't in the bottom row
Added/updated relevant tests, including one for testing going between the different modes.
=> Support for paint-on, slight rework to roll-up, misc fixes

lib/m2ts/caption-stream.js, test/caption-stream.test.js
When going through caption stuff with @ldayananda, I noticed that several of the tests I committed were missing helpful comments for the control codes. In that process, I noticed a couple tests that were doing some dumb things, so now they are no longer doing dumb things.
Also realized that there was no test for special/extended characters for CC2-CC4, so I added a small test. Full character mapping functionality is tested for `Cea608Stream`, but only for CC1.
=> add some docs and a couple small test changes

lib/tools/ts-inspector.js, test/transmuxer.test.js, test/ts-inspector.test.js, test/utils.js
Also moved some reusable functions from the transmuxer tests to a utils module (might be easiest to review the two separate commits).
=> Fix TS probe parsing of audio PES when there's only one packet

lib/mp4/transmuxer.js, test/transmuxer.test.js
There is a `keepOriginalTimestamps` flag which is intended to avoid adjusting timestamps when transmuxing from TS -> MP4. However, we do not respect this flag when returning captions and ID3 tags parsed out of the video data, leading to the captions and ID3 cues being out-of-sync with the video data.
Releasing this might be tricky as users may be depending on this behavior. A couple of ways we could do this:
- release as a major version, with captions and ID3 cues respecting the flag
- make a new flag to avoid adjusting the timing for captions and ID3 cues specifically
The downsides of the first is that any users relying on the current behavior with `keepOriginalTimestamps` would have to adjust caption times to start at zero if the TS segments do not start at zero.
=> fix(mp4/Transmuxer): respect keepOriginalTimestamps for captions and ID3 in mp4

lib/m2ts/caption-stream.js, test/caption-stream.test.js
It's possible for a base row to be selected with a number of roll up rows that would be invalid. e.g:
base row: 1
number of roll-up rows: 3
This should do two things:
- set a correct base row and `topRow_` in the parsing code
- avoid throwing exceptions from the caption parsing code, and logs a message instead
=> fix(captions): handle case where invalid base row is selected with roll-up mode

lib/tools/mp4-inspector.js
Needed for videojs/http-streaming#207.
Exposes `parseSidx` in addition to the other box types.
=> Expose parseSidx in mp4-inspector

.travis.yml, test/karma/karma.conf.js
The build seems to be failing with headless Chrome, let's switch back to the standard browsers.
=> test: use standard browsers

lib/mp4/transmuxer.js, test/transmuxer.test.js
The video timing info can be useful for determining the duration of a segment (both presentation and decode), as well as any time prepended due to the addition of GOPs for alignment.
=> Trigger videoTimingInfo on transmuxer with relevant timing info and prepended GOP duration

lib/tools/ts-inspector.js
=> Fix for crash on missing PTS/DTS in ts-inspector

lib/m2ts/caption-stream.js, test/caption-stream.test.js
I noticed that XDS and Text packets aren't being ignored, and those may interfere with captions.
To ignore the packets, I do similar to what's done before any active channel is set -- I set the `activeCea608Channel` for the field to `null` so that packets are dropped.
Note: I've never seen Text packets in real life, so if anyone has any sources, please share!
=> Ignore XDS and Text packets

lib/mp4/transmuxer.js, lib/partial/transmuxer.js, package-lock.json
Right now we only fire `trackinfo` for `tsPipelines`, but  we should fire it for `aacPipelines` as well.
=> fix: Fire trackinfo for audio only transmuxers

lib/mp4/transmuxer.js, lib/partial/audio-segment-stream.js, lib/partial/transmuxer.js, test/transmuxer.test.js
For fmp4 playlists with ts segment discontinuities the track ids of the fmp4 files and the ts segments that we transmux to fmp4 must match up.
=> Feat: change remux after initial creation

lib/m2ts/timestamp-rollover-stream.js, lib/mp4/transmuxer.js
We saw an issue where some streams had a discontinuity and DTS rollover in one track (e.g. video), but not in another (e.g. audio). The effect of this was that the audio would be interpreted as being ~23 hours in the past and would be thrown out.
For live streams, this meant that the stream would abruptly halt and ultimately cause the player to time out. For VOD streams - at least, in the test case we have - this means audio would be dropped, but video would continue to play.
The solution here is to use a single, shared `TimestampRolloverStream` for cases where this is possible.
=> fix: Fix an issue where a rollover in only one audio or video track could cause the other to be dropped.

lib/mp4/transmuxer.js
There are scenarios where we parsed timed-metadata but did NOT find any video or audio data. For timing reasons, we can't map the timed-metadata to a proper cue-time until we have received PTS timing data from audio or video tracks. This change causes the transmuxer to hold onto any parsed timed-metadata info instead of emitting it, treating that timed-metadata like it came from the NEXT segment (which hopefully has content) so that we can do a proper mapping to generate the cues' startTime and endTime.
=> fix: If there isn't any video OR audio track data, just emit done

lib/codecs/h264.js
Significant speedup in (pre-Chromium) Edge, especially for high
bitrates such as uncompressed or lightly-compressed frames.
Previously, buffer.byteLength and buffer.length got looked up
multiple times per byte processed in Edge, leading to higher
CPU usage.
=> Cache buffer.byteLength in NalByteStream.push

lib/mp4/caption-parser.js
Currently, if the `trackId` is zero, the CaptionParser thinks it hasn't found an init segment yet and stores the segment for later inspection.  This PR changes the `trackId` checks in CaptionParser to allow for a `trackId` of zero, and thus the captions can then be parsed.
=> Parse captions from tracks with trackId of zero

lib/mp4/transmuxer.js
Previous to TBA/LHLS we did code that equated to `metadataTsToSeconds` on `id3`s. In master we do `videoTsToSeconds`. The code itself seems to think that `metadataTsToSeconds` should be called as it passes all the parameters for it, and it fixes an issues where cues are not firing at the correct time, since they are trying to use video time and not metadata time.
This means we can close #292 (hopefully)
=> fix: use metadataTsToSeconds for id3 as we did previously

lib/tools/mp4-inspector.js, test/mp4-inspector.test.js
According to the ISO BMFF spec, the base media decode time is stored as an unsigned integer within the `tfdt` box. The mp4 probe [already returns](https://github.com/videojs/mux.js/blob/master/lib/mp4/probe.js#L167-L170) an unsigned integer, but the mp4 inspector does not. This PR corrects that behavior, ensuring that the same unsigned value is returned by both the probe and inspector.
=> fix: mp4Inspector should return unsigned baseMediaDecodeTime

lib/mp4/probe.js, lib/tools/mp4-inspector.js, test/mp4-probe.test.js
This moves some proposed fmp4 box parsing logic from a [VHS PR](https://github.com/videojs/http-streaming/pull/660) into the mux.js mp4 probe module, a more fitting home. I also moved `parseType()` and `findBox()` out of the mp4 probe and into the mp4-inspector as a first step to remove some duplication between the probe and inspector files. We should move all box-parsing logic into the inspector, and then use those parsing functions in the probe rather than have duplicate logic in both places. I'll save that refactoring for a separate PR.
More details about `compositionStartTime()` and the reason for adding it can be found in the VHS PR linked above.
=> feat: add compositionStartTime mp4 probe function

lib/mp4/mp4-generator.js
This change improve performance by 3X (measured with node.js)
Instead of using array.concat when we iterate the frames (Which create
a new array + copy data from old to new for each iteration)
We are now creating a one time single array with the size of the
final array and filling it up.
=> perf: Single allocation of Uint8Array in trun.

lib/constants/audio-properties.js, lib/constants/video-properties.js, lib/mp4/transmuxer.js, lib/partial/audio-segment-stream.js, lib/partial/transmuxer.js, lib/partial/video-segment-stream.js, test/partial.test.js, test/transmuxer.test.js
`timelineStartInfo.baseMediaDecodeTime` is `0` when `keepOriginalTimestampOffsets` is `true`. This causes earliestAllowedDts to be much higher than it should be, which means that almost all audio is trimmed when seeking backwards for live stream videos. 
Track `baseMediaDecodeTime` even though we don't intend to use it for most things when `keepOriginalTimestampOffsets` is `true`. That way we can use it to get the real timeline start dts.
This fixes the stream mentioned in https://github.com/videojs/http-streaming/pull/624#issuecomment-544506799 that can be tested by turning on the `liveui` in the vhs test page and linking in this version of mux.js
=> fix: always calculate the earliest allowed dts using baseMediaDecodeTime

lib/tools/mp4-inspector.js, test/mp4-inspector.test.js
This is a fix for issue videojs/mux.js#155 ... the fractional portion of the tkhd box's height and width was being calculated incorrectly (divided by 16, instead of shifting right by 16 or divided by 65536).
=> Fixes fixed point calculation of tkhd box's height and width.

lib/data/silence.js, lib/mp4/audio-frame-utils.js
Saves about ~10-20ms of script loading time in the browser in slow browsers/computers.
=> perf: make cone of silence lazy

lib/mp4/caption-parser.js
Do a null check around lastMatchedSample in caption-parser. While having
the null check makes sense, it's possible the content is malformed or
that we're doing a miscalculation somewhere else in the caption-parser.
So, while this will help with #233, we won't close #233 until we can
spend a bit more time investigating the underlying issue.
=> fix(caption-parser): do not fail when first sei sample is null

lib/mp4/transmuxer.js, test/transmuxer.test.js
Because the first segment after a discontinuity may have a smaller timestamp than the first segment overall, the post-discontinuity segment may have its audio completely removed.
With the keepOriginalTimestamps flag, this subtle form of timestamp manipulation should be avoided, leaving apps in complete control of the timestamps.
Closes #328
=> fix: Do not trim audio output when keepOriginalTimestamps is set

lib/tools/caption-packet-parser.js, test/caption-stream.test.js
Update of https://github.com/videojs/mux.js/pull/330.
=> fix: skip DTG1 packets in parseSei

lib/mp4/transmuxer.js, lib/partial/transmuxer.js, test/partial.test.js, test/transmuxer.test.js
Reverts the part of #317 that always uses `baseMediaDecodeTime` to trim audio even when `keepOriginalTimestamps` is on. It seems like the actual fix fo the issue in #317 was fixed with #329. I have also included the updates from #329 into the partial transmuxer in this pull request so that it remains up to date. 
Right now this code breaks alternative audio tracks as we do not trim audio as expected and switching to an alternative audio track causes us to infinite buffer due to a gap.
=> revert: use baseMediaDecode to set earliest dts (#317)

lib/mp4/probe.js, test/mp4-probe.test.js
Previously, getTracks used the track header box version for determining
the version of the media header box. But the versions can be different. This
change uses the version of the mdhd box instead.
This logic should also better match the timescale mp4 probe function: https://github.com/videojs/mux.js/blob/master/lib/mp4/probe.js#L54
Source used for testing: https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd
=> fix: return proper timescale for version 1 mdhd in mp4 probe getTracks

lib/mp4/caption-parser.js
Saves us 435 gzipped bytes in VHS
=> refactor: use inspect.findBox, rather than importing probe

lib/aac/utils.js, lib/mp4/transmuxer.js, lib/partial/transmuxer.js, test/aac-utils.test.js, test/transmuxer.test.js
ID3 tags are not specific to aac data. Almost any audio container format can use it. AAC has a specific syncbyte `0xFFF1` that we need to look for instead.
=> fix: ID3 does not indicate aac data

lib/aac/utils.js, test/aac-utils.test.js
handle multiple id3 sections at the start of aac data.
=> fix: handle recursive id3 in isLikelyAacData

lib/mp4/probe.js
`flac` comes in as `fLaC` which is an invalid codec in chrome unless it is lower case. `opus` comes in as `Opus` and that has the same issue.
=> feat: support codec probes for opus/flac

lib/tools/parse-sidx.js, test/mp4-inspector.test.js
=> fix(mp4Inspector): read version 1 sidx boxes

lib/flv/transmuxer.js, lib/m2ts/caption-stream.js, lib/mp4/transmuxer.js, lib/partial/transmuxer.js, test/caption-stream.test.js
This options flow through the transmuxer into CaptionStream.
=> feat(CaptionStream): add flag to turn off 708 captions

lib/m2ts/m2ts.js, test/transmuxer.test.js
**Description**
This is a fix for ts files that carry PES packets of framed data from the previous ts fragment. This addresses the `ERROR: (CODE:3 MEDIA_ERR_DECODE)` for the cause
```
The media playback was aborted due to a corruption…media used features your browser did not support
```
or
```
[video|audio] append of [x]b failed for segment #[n]
```
**Content**
The stream I was able to reproduce the bug with is https://e3e2p5m2.ssl.hwcdn.net/hls/main.m3u8. I was able to record when the bug occurred and uploaded the recorded content to https://drive.google.com/drive/folders/174ef0f6DOdMaXI6f3CLYSw_9H5emxzM0?usp=sharing. There is a generated VOD manifest for the recorded content. 
**Steps to reproduce**
I was able to produce this bug using Video.js (v7.11.4).
If you try to playback the …
=> fix: ignore buffered packet data with no pes header

lib/tools/ts-inspector.js
if baseTimestamp is NaN, we do not set the baseTimestamp for the track... This means when video.js http-streaming uses mux.js to transmux from TS to MP4, the probe timestamp results use a 0-based baseMediaDecodeTime and the actual transmux uses a DTS-based baseMediaDecodeTime.
If not doing a partial transmux, this causes video.js to use a start time of 0 (from probe) and an end time of DTS (whatever that is). If DTS happens to be negative, then the duration calculated for the first segment ends up being ~25 hours (close to 2^33, the size of the DTS field, because DTS is being interpreted unsigned)
See:
https://github.com/videojs/http-streaming/blob/main/src/media-segment-request.js#L289-L308
https://github.com/videojs/http-streaming/blob/main/src/media-segment-request.js#L329-L339
=> Check if baseTimestamp is NaN

lib/tools/ts-inspector.js
We currently have issues with ts files that add stream types after the first program map table as we only look at the first one. So if audio were to be added in a subsequent program map table we wouldn't know to account for it.
=> fix: inspect all program map tables for stream types

lib/m2ts/m2ts.js
Always emit trackinfo, even if we didn't process a pmt.
=> fix: on flush if a pmt has not been emitted and we have one, emit it

lib/codecs/adts.js, test/transmuxer.test.js
Right now we run into an issue if adts contains data between sync words that is not part of a frame. 
Example
We have an adts file where bytes 0-5 are garbage, and after that the file is like normal. This is what would happen right now:
1. bytes 0-5 are garbage so they fail the syncword check and `i` is now incremented up to `5`.
2. We parse that frame successfully as 400 bytes long.
3. Then we remove those 400 bytes from the front of the buffer using subarray, but we do not reset `i` to `0`
4. On the next loop we check `buffer[i]` for a syncword but `i` is still `5` so we skip everything else in the buffer until the next syncword and further aggravate the problem by incrementing `i` some more.
=> fix: prevent skipping frames on garbage adts data

lib/codecs/adts.js, lib/mp4/transmuxer.js
Report warnings, debug, and error information via events.
=> feat: add general error/warn/debug log events

lib/codecs/h264.js, test/transmuxer.test.js
While this doesn't give us the absolute width when we have a `sarRatio`, we don't want to use the absolute width. This is because we already encode the `sarRatio` in the `pasp` atom of our mp4 output. By encoding the `sarRatio` and an absolute width, the width is skewed even further unless the decoder looks directly at the nal units and calculates it itself. Example:
* `sarRatio` is `0.5`
* `width` is `640` without `sarRatio`
How it is now with `sarRatio` width would get set to `320` and then when the decoder see's the `pasp` atom with `sarRatio` it will think that width is `160`. Some decoders will ignore all these values on use nal units to calculate the width, but mobile Samsung Chrome on Android 11 will not. This causes a media decode error as the actual width of the video is `320`. …
=> fix: Do not scale width by sarRatio, we already generate a pasp box with sarRatio information.

lib/mp4/transmuxer.js, test/transmuxer.test.js
This PR replaces #394. It removes build artifacts and address the change in the test suggested by @brandonocasey.
/cc @gkatsev 
Adds an option `firstSequenceNumber` to Transmuxer.
Can be used like this:
```js
new Transmuxer({ firstSequenceNumber: 10 });
```
This is passed in to VideoSegmentStream and AudioSegmentStream.
When mfhd boxes are constructed, the starting sequence number will be
taken from that option. The default value is zero.
This is useful for generating segmented streams out of order. Out of
oder processing allows for restart, parallelism, or random seeking into
source material.
=> Adds mfhd starting sequence option to Transmuxer

lib/m2ts/metadata-stream.js, test/metadata-stream.test.js
Enables sending ID3 tag with as many frames as could be parsed.
Without this change [this.trigger('data', tag)](https://github.com/videojs/mux.js/blob/main/lib/m2ts/metadata-stream.js#L249) wasn't called if stumbled upon malformed ID3 tag/frame.
Beneficiaries: Tellos Z/IP Stream encoder produces ID3 data with `TIT2`, `WOAF` and `TENC` frames, from which only `TIT2` can be parsed by mux.js, so let's take those frames that have been parsed.
Additionally, I'll take a look at mux.js' ID3 parser and try to find out if that metadata is really malformed or it's an issue with the parser.
=> Send ID3 tag even when it has malformed content

lib/m2ts/metadata-stream.js, test/metadata-stream.test.js
This PR adds parsing:
- Text information frames [[ID3v2.4.0](https://id3.org/id3v2.4.0-frames) section 4.2.]
- URL link frames [[ID3v2.4.0](https://id3.org/id3v2.4.0-frames) section 4.3.]
- Attached picture frames (with "-->" MIME type support) [[ID3v2.4.0](https://id3.org/id3v2.4.0-frames) section 4.14.]
Tested in unit tests and by parsing [media-uq37ul2b4_b64000_330729098.ts.zip](https://github.com/videojs/mux.js/files/8785831/media-uq37ul2b4_b64000_330729098.ts.zip)
that results in the following metadata being sent to the client:
=> ID3: add parsing text, link and APIC frames

lib/mp4/emsg.js, test/mp4-probe.test.js
Use the number utils `getUint64` function and change uses of `Array.from` to `[].slice.call` in unit tests for IE11 support.
=> fix: emsg ie11 test failures

.github/workflows/github-release.yml, .github/workflows/release.yml, COLLABORATOR_GUIDE.md
Note: `NPM_TOKEN` should be added as repo's secrete
=> chore: add npm publish in release workflow

lib/flv/coalesce-stream.js, lib/m2ts/caption-stream.js, lib/mp4/caption-parser.js, lib/mp4/transmuxer.js, package-lock.json, test/caption-parser.test.js, test/caption-stream.test.js
NOTE: This will require a major version update, as this changes how the caption data is sent to VHS. This was necessary, as we were previously combining text that can have different positioning data on these messages. This will require changes in VHS and video.js once this is released.
Previously for CEA-608 captions, we were completely ignoring positioning data and just centering all captions at the bottom of the screen. This change allows us to take advantage of our parsing and including this positioning data. The 'line' field represents the row on which to display the text from 1-15, and the `position` field represents where the caption should be displayed horizontally on a scale from 1-100 (although the spec states we should lock it between 10-80).
See: …
=> feat: add position data to captions

lib/m2ts/caption-stream.js, test/caption-stream.test.js
We were seeing issues with non-latin 708 captions not being displayed correctly. It appears that the issue that we are not always handling multi-byte characters correctly.
This fix proposes that in the case where we see a multi-byte character without a pre-designated decoder, we send the byte array through a function to turn it into a hex string, and then from there decode it into the character.
Example Test Playlist: https://solutions.brightcove.com/wseymour/708-testing/playlist.m3u8
Before: 
After:
=> fix: 708 captions multi-byte char fix

lib/m2ts/timestamp-rollover-stream.js
The rollover stream expects data from the elementary stream.
The elementary stream can push forward two types of data
- Parsed Video/Audio/Timed-metadata PES (packetized elementary stream) packets
- Tracks metadata from PMT (Program Map Table)
The rollover stream expects PTS/DTS info to be available since it stores the last DTS.
We should ignore non-PES packets since they may override lastDTS to undefined.
The last DTS is important to signal the next segments about rollover from the previous segments.
Let's review the following example:
we have segment-1 which is the first segment from a new timeline(disc):
with pts starting from 0
and “negative” dts (rolled back by dtsPtsOffset)
PTS = 0
DTS = 2^33 - dtsPtsOffset
we rollover values using the rollover stream:
PTS = 2^33
DTS = 2^33 - …
=> fix: ignore non-pes packets in the rollover stream

lib/m2ts/caption-stream.js
We were seeing some odd results with the following stream, regarding captions failing:
https://solutions.brightcove.com/slevitas/jiras/cisco-bc-64040/capture/m-chunklist.m3u8
This fix ensures that even if for some reason a PAC packet seems to have an invalid row, the player will not fail
=> fix: 608 caption out of bound rows
