videojs/mux.js

- package.json
npm run has access to .bin commands
> Shorten npm test command

- lib/metadata-stream.js
- lib/transmuxer.js
- test/id3-generator.js
- test/index.html
- test/karma.conf.js
- test/metadata-stream-test.js
- test/transmuxer-test.js
Pull in ID3 metadata parser and tests.
> Add metadata stream

- lib/transmuxer.js
- test/transmuxer-test.js
First attempt at combining video/audio back into a single output segment.
Caveats:
* Stripped out the part where we try to pull in baseMediaDecodeTime of segments that are too far apart.
> Cross streams

- lib/transmuxer.js
- test/transmuxer-test.js
Two small fixes here:
* If a PMT has not been seen yet, defer processing PES packets until we have one.
* Clear the PPS and track config between segments so that we handle rendition switching correctly!
> Minor fixes

- debug/css/main.css
- debug/index.html
Remove some code duplication. Layout and style the page a bit differently so big videos don't break things and it's easier to see the form. Allow the "active" input to be selected without modifying the source of the page.
> Clean up the debug page

- debug/index.html
..because changing the codecs string every time is annoying!
> Save and restore the state of inputs in the debugger across page loads..

- README.md
- package.json
- test/karma.conf.js
Make some minor modifications to the npm scripts. `browserify` doesn't automatically make the dist/ directory and build isn't a built-in task.
> Clean up npm scripts

- lib/flv/flv-tag.js
- lib/utils/exp-golomb.js
Allows IE11 to run mux.js without erroring.
> Removed console.assert statements from code

- .npmignore
- package.json
> Only upload source files to npm

- lib/mp4/transmuxer.js
- test/transmuxer.test.js
> add audio track info to event that are sent to MSE

- lib/codecs/h264.js
- lib/tools/mp4-inspector.js
- test/transmuxer.test.js
> Fixed Empty nal units

- lib/mp4/transmuxer.js
> Fix the condition in groupNalsIntoFrames_ that could be true even if frames.length was zero

- lib/mp4/probe.js
- test/mp4-probe.test.js
Correct parsing outputs to handle 64-bit fields when probing mp4s.
> Parse v1 boxes

- lib/m2ts/caption-stream.js
- test/caption-stream.test.js
Minor cleanup to #107 that fixes #100
> 608 captions stable-sort for Chrome

- package.json
https://github.com/videojs/mux.js/issues/131
> Only use browserify-shim for building tests

- .travis.yml
- package.json
- test/karma/karma.conf.js
Also disable firefox since it's causing timeout issues at the moment
> Fix integration with TravisCI so tests are actually run

- package-lock.json
- package.json
> ignore: build on prepublish

- .travis.yml
- package-lock.json
- package.json
- test/karma/karma.conf.js
Headless Chrome should take care of everything. Also trying to fix the build.
> Simplify .travis config

- lib/mp4/transmuxer.js
- test/transmuxer.test.js
> Add option to keep original timestamps in MP4 transmuxer.

- lib/mp4/transmuxer.js
> fix code doc

- lib/tools/mp4-inspector.js
Another change for https://github.com/videojs/http-streaming/issues/176
> fix: remove usage of global

- .nvmrc
- package-lock.json
- package.json
Security update and use the carbon tag for nvm
> ignore: update npm-run-all to 4.1.5

- lib/tools/mp4-inspector.js
This is needed for an upcoming fix in VHS.
> feat: Expose traf box parser on mp4-inspector

- lib/mp4/transmuxer.js
- lib/partial/audio-segment-stream.js
- lib/partial/video-segment-stream.js
See https://github.com/videojs/http-streaming/pull/624
It seems that most browsers use pts these days, and we get better results with it.
> fix: emit pts values instead of dts

- lib/partial/video-segment-stream.js
This was missed in #300, we also want to send PTS here.
> send videoFramePts with data event for partial video

- README.md
> docs: add library module docs and transmuxer options docs

- .gitignore
- package-lock.json
- package.json
- scripts/netlify.js
This allows us to test vhs with mux.js changes using netlify
> test: add vhs test page for netlify testing

- lib/m2ts/m2ts.js
```m2tsStreamTypes``` and ```StreamTypes``` are pointing to the same file...
> Remove duplication of StreamType

- lib/tools/caption-packet-parser.js
- test/caption-stream.test.js
See the code for when this happens.
> fix: 708 caption error caused by non GA94 caption

- lib/tools/mp4-inspector.js
This resolves a TODO in mp4-inspector.js about v1 trun boxes.
Closes #332
> fix: parse signed CTO in v1 trun boxes

- package.json
- scripts/insert-license-header.js
> chore: Prepend license header into minified bundles

- lib/mp4/caption-parser.js
- lib/mp4/find-box.js
- lib/mp4/parse-type.js
- lib/mp4/probe.js
- lib/mp4/transmuxer.js
- lib/tools/mp4-inspector.js
- lib/tools/parse-sample-flags.js
- lib/tools/parse-sidx.js
- lib/tools/parse-tfdt.js
- lib/tools/parse-tfhd.js
- lib/tools/parse-trun.js
See https://github.com/videojs/http-streaming/pull/863
> refactor: dedupe code into modules for smaller vhs

- lib/m2ts/caption-stream.js
> fix: null check sei payload in caption stream

- lib/mp4/audio-frame-utils.js
- lib/mp4/transmuxer.js
- test/transmuxer.test.js
See linked VHS PR for more details: https://github.com/videojs/http-streaming/pull/1040
> feat: add audioSegmentTimingInfo event to match videoSegmentTimingInfo

- lib/tools/ts-inspector.js
> fix: ts inspect ptsTime/dtsTime typo

- CHANGELOG.md
- README.md
Update README and add the breaking changes to the CHANGELOG.
> chore: update v7.0.0 documentation

- README.md
Resolves https://github.com/videojs/mux.js/issues/407 and https://github.com/videojs/mux.js/issues/323
Context is in [407](https://github.com/videojs/mux.js/issues/407).
A mini contribution for https://hacktoberfest.com/ if you'll be kind to add the label `hacktoberfest-accepted` for this PR. Thanks!
> change code example transmuxer event listeners
